package solvers.volterra

import numerics.GaussLegendre
import splines.GeneratingSystem
import splines.Grid
import splines.MinimalSplineBasis
import org.junit.jupiter.api.Tag
import problems.volterra.VolterraProblem
import java.util.concurrent.Callable
import java.util.concurrent.CyclicBarrier
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import kotlin.random.Random
import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * BITWISE equivalence of the cached and uncached application of the Volterra
 * operator: [VolterraOperator.apply] with a [VolterraOperator.IntegrandCache] must give
 * THE SAME double as [VolterraOperator.apply] with a function.
 *
 * Why exactly such a test is needed. Memoizing the values of `u` at the nodes of full cells is a pure
 * optimization of the hot path, and its correctness has so far been confirmed only indirectly:
 * the characterization baseline (1366 E_h values, tolerance 1e-9) matched bit for bit. But the baseline
 * covers a SPECIFIC set of configurations; the cache could diverge from the original on other
 * inputs, above all at the boundaries, where the selection of "full" cells depends on a comparison with
 * the threshold [VolterraOperator.breakpointInclusionEps]. This test closes the hole
 * by a direct check on a matrix of boundary cases.
 *
 * ON THE SCALE OF THE INTERVAL: the inclusion threshold is RELATIVE (proportional to `b-a`), so
 * the grids are taken not only on the default `[0,1]`, but also on intervals of LARGE scale
 * (`[0,1000]`, `[-500,500]`), where an absolute threshold of 1e-15 would sink below the ulp of the nodes. Without them
 * the new behaviour of the threshold would not be checked at all (the characterization baseline is also shot
 * only on `[0,1]`).
 *
 * Why the comparison is BITWISE and not with a tolerance. The requirement for stages 1-7 of the refactoring is
 * behavioural neutrality: the baseline is not regenerated by a single line. Multiplication of
 * doubles is non-associative, so even a permutation of the factors in the accumulation of the sum
 * (`(half*w*K)*u` instead of `half*w*(K*u)`) changes the last bit of the result and "drifts"
 * in the baseline. A test with a tolerance would miss such a regression, a bitwise one catches it.
 *
 * The coverage matrix in `t` (see [boundaryTs], [nodeThresholdTs], [interiorTs]):
 * `t = a` (empty integral), `t = b` (all cells full), `t` EXACTLY at a grid node,
 * `t` in a neighbourhood of a node (±1e-16, ±1e-15, ±1e-14 — around the threshold itself),
 * `t` inside the first cell (there are no full cells yet), `t` inside the last cell
 * and several arbitrary points in the middle of the interval.
 *
 * The matrix over grids and data: uniform (n = 4, 8, 16), geometric and
 * graded (substantially non-uniform); the kernels of the three model problems of the project
 * (`V2`: 1/(1+t+s), `V2exp`: exp(-(t-s)^2), `V2win`: t-s); the integrands are
 * smooth, polynomial and TWO spline ones of the same kind as really arrive in
 * `VolterraSecondKindSolver.applyL` (a spline value from coefficients and a basis `omega_j`).
 */
@Tag("fast")
class VolterraIntegrandCacheEquivalenceTest {

    private val quad = GaussLegendre(8)

    /** Baseline nodes/weights on [-1,1] — needed by the diagnostics to reproduce the arithmetic. */
    private val refNodes = quad.refNodesWeights().first
    private val refWeights = quad.refNodesWeights().second

    // --- Description of the combinations -----------------------------------------

    private class GridCase(val name: String, val grid: Grid)
    private class KernelCase(val name: String, val kernel: KernelV)
    /**
     * @param definedOutsideSegment whether `u` is defined OUTSIDE the grid interval. Since item 8.3
     *   the spline `u` are NOT defined there and throw `IllegalArgumentException` instead of
     *   silent extrapolation; the smooth and polynomial ones are defined everywhere.
     */
    private class IntegrandCase(
        val name: String,
        val definedOutsideSegment: Boolean,
        val u: (Double) -> Double,
    )
    private class TCase(val t: Double, val label: String)

    /**
     * The grids are taken SMALL, but of different families: a divergence of the cache from the original is a property
     * of the structure of the partition (the cell selection threshold) and not of the size n, so large grids
     * would add nothing but would push the test out of the budget of the fast suite.
     */
    private fun gridCases(): List<GridCase> = listOf(
        GridCase("uniform n=4", Grid.uniform(4)),
        GridCase("uniform n=8", Grid.uniform(8)),
        GridCase("uniform n=16", Grid.uniform(16)),
        GridCase("geometric n=8 R=2", Grid.geometric(8, R = 2.0)),
        GridCase("graded n=8 ratio=2", Grid.graded(8, ratio = 2.0)),
        // Intervals of LARGE scale: here the inclusion threshold is no longer equal to 1e-15
        // (it is relative), and it is exactly they that cover the new behaviour: on them
        // the absolute 1e-15 lies below the ulp of the nodes (ulp(1e3) ~ 2.3e-13).
        GridCase("uniform n=8 on [0,1000] (large scale)", Grid.uniform(8, 0.0, 1000.0)),
        GridCase("uniform n=8 on [-500,500] (large scale, sign-changing)", Grid.uniform(8, -500.0, 500.0)),
        GridCase("graded n=8 ratio=2 on [0,1000]", Grid.graded(8, 0.0, 1000.0, ratio = 2.0)),
    )

    /** The kernels come from the model problems of the project (fixtures), they are not invented. */
    private val kernelCases = listOf(
        KernelCase("V2 K=1/(1+t+s)", VolterraProblem.V2.kernel),
        KernelCase("V2exp K=exp(-(t-s)^2)", VolterraProblem.V2exp.kernel),
        KernelCase("V2win K=t-s", VolterraProblem.V2win.kernel),
    )

    /**
     * The integrands. The spline variants are mandatory: it is exactly they that pass through
     * `applyL` in the solver (`basis.evalSpline(c, s)` in `sloan`/`iteratedKulkarni`
     * and `basis.omega(i, s)` in `matrixM`), and a spline is piecewise defined and therefore sensitive
     * to which side of a node the argument fell on.
     */
    private fun integrands(grid: Grid): List<IntegrandCase> {
        val basis = MinimalSplineBasis(GeneratingSystem.B, grid)
        // Arbitrary but deterministic coefficients (not "nice" numbers, so that
        // all bits of the mantissa take part in the accumulation of the sum).
        val coeffs = DoubleArray(grid.n + 2) { i -> Math.sin(0.7 * i + 0.3) }
        return listOf(
            IntegrandCase("smooth sin(3s)*exp(-s/2)", definedOutsideSegment = true) { s ->
                Math.sin(3.0 * s) * Math.exp(-0.5 * s)
            },
            IntegrandCase("polynomial 1-2s+3s^2-s^3", definedOutsideSegment = true) { s ->
                1.0 - 2.0 * s + 3.0 * s * s - s * s * s
            },
            // Spline ones: defined ONLY on the grid interval (item 8.3).
            IntegrandCase("spline evalSpline(c,s) (as in sloan)", definedOutsideSegment = false) { s ->
                basis.evalSpline(coeffs, s)
            },
            // `omega_j` is an exception: it cuts off points outside the support BEFORE calling
            // `intervalOf`, and the support lies inside the interval, so outside the interval it
            // regularly returns 0 and stays suitable for a bitwise comparison at t>b.
            IntegrandCase("basis spline omega_1(s) (as in matrixM)", definedOutsideSegment = true) { s ->
                basis.omega(1, s)
            },
        )
    }

    // --- Sets of t values ---------------------------------------------------------

    /** The ends of the interval: at `t=a` the integral is empty, at `t=b` ALL cells are full. */
    private fun boundaryTs(grid: Grid): List<TCase> = listOf(
        TCase(grid.a, "t=a=${grid.a} (lower bound, the integral is empty)"),
        TCase(grid.b, "t=b=${grid.b} (upper bound, all cells full)"),
    )

    /**
     * The grid nodes and their neighbourhood. This is the MOST dangerous place: both paths decide "whether to
     * include the node x_j in the partition" by the comparison `x_j < t - 1e-15`, and any divergence in this
     * decision changes both the number of full cells and the bounds of the truncated cell. The shifts 1e-16 /
     * 1e-15 / 1e-14 are chosen around the threshold itself: below it, at it, above it.
     */
    private fun nodeThresholdTs(grid: Grid): List<TCase> {
        val res = ArrayList<TCase>()
        for (j in 1 until grid.n) {
            val x = grid.x(j)
            res.add(TCase(x, "t=x_$j=$x EXACTLY a grid node"))
            for (d in listOf(1e-16, 1e-15, 1e-14)) {
                res.add(TCase(x - d, "t=x_$j-$d (x_$j=$x)"))
                res.add(TCase(x + d, "t=x_$j+$d (x_$j=$x)"))
            }
        }
        return res
    }

    /** Interior points: the first cell (no full cells), the last cell, the middle. */
    private fun interiorTs(grid: Grid): List<TCase> {
        val res = ArrayList<TCase>()
        val x1 = grid.x(1)
        val xLast = grid.x(grid.n - 1)
        res.add(TCase(grid.a + 0.25 * (x1 - grid.a), "t in the first quarter of the FIRST cell (no full cells)"))
        res.add(TCase(0.5 * (grid.a + x1), "t in the middle of the FIRST cell (no full cells)"))
        res.add(TCase(0.5 * (xLast + grid.b), "t in the middle of the LAST cell"))
        res.add(TCase(grid.b - 0.25 * (grid.b - xLast), "t in the last quarter of the LAST cell"))
        for (frac in listOf(0.137, 0.381, 0.5, 0.6180339887498949, 0.9042)) {
            res.add(TCase(grid.a + frac * (grid.b - grid.a), "t=a+$frac*(b-a) (an arbitrary interior point)"))
        }
        return res
    }

    // --- Tests ----------------------------------------------------------------

    /**
     * The ends of the interval. At `t <= a` both paths must return exactly `0.0` by the early
     * return, at `t = b` the longest variant works: n-1 full cells from the cache
     * plus the truncated cell `[x_{n-1}, b]`.
     */
    @Test fun boundaries_cachedMatchesUncachedBitwise() {
        val stats = compareAll("ends of the interval") { grid -> boundaryTs(grid) }
        assertNonDegenerate(stats)
    }

    /**
     * The grid nodes and the neighbourhood of the threshold [VolterraOperator.breakpointInclusionEps].
     * It is exactly here that the cached path (the counter `included` in the `while` loop) could select
     * a different number of full cells than `subBreakpoints` (a `for` loop with a `break`).
     */
    @Test fun gridNodesAndThresholdNeighborhood_cachedMatchesUncachedBitwise() {
        val stats = compareAll("grid nodes and the neighbourhood of the inclusion threshold") { grid -> nodeThresholdTs(grid) }
        assertNonDegenerate(stats)
    }

    /**
     * THE NEIGHBOURHOOD OF THE THRESHOLD ITSELF, computed from the scale of the concrete grid.
     *
     * [nodeThresholdTs] shifts `t` by FIXED 1e-16/1e-15/1e-14 — that was a
     * neighbourhood of the threshold while the threshold was absolute. Now the threshold depends on
     * the scale of the interval, and on `[0,1000]` those shifts are three orders SMALLER than the threshold
     * (and generally below the ulp of the nodes), that is, they no longer touch the switching point of the
     * decision itself. Here the shifts are taken FROM THE ACTUAL threshold of the operator, so the
     * boundary "include / do not include the node" is checked on ANY scale.
     */
    @Test fun scaledThresholdNeighborhood_cachedMatchesUncachedBitwise() {
        var comparisons = 0
        var crossings = 0
        for (g in gridCases()) {
            val eps = VolterraOperator(kernelCases[0].kernel, g.grid, quad).breakpointInclusionEps
            val ts = ArrayList<TCase>()
            for (j in 1 until g.grid.n) {
                val x = g.grid.x(j)
                // Exactly at the threshold, slightly below and slightly above — in units of the THRESHOLD ITSELF.
                for (mult in listOf(0.5, 1.0, 2.0, 10.0)) {
                    ts.add(TCase(x + mult * eps, "t=x_$j+$mult*eps (eps=$eps, x_$j=$x)"))
                    ts.add(TCase(x - mult * eps, "t=x_$j-$mult*eps (eps=$eps, x_$j=$x)"))
                }
                ts.add(TCase(Math.nextAfter(x + eps, Double.NEGATIVE_INFINITY), "t=nextDown(x_$j+eps)"))
                ts.add(TCase(Math.nextAfter(x + eps, Double.POSITIVE_INFINITY), "t=nextUp(x_$j+eps)"))
            }
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid)) {
                    val cache = op.integrandCache(integrand.u)
                    for (tc in ts) {
                        val expected = op.apply(tc.t, integrand.u)
                        val actual = op.apply(tc.t, cache)
                        comparisons++
                        assertBitwise(expected, actual) {
                            report("neighbourhood of the RELATIVE threshold eps=$eps", g, k, integrand, tc, expected, actual, op, cache)
                        }
                    }
                }
            }
            // The set is not degenerate: among the points there are also ones where the number of full cells DIFFERS
            // on the two sides of the threshold, otherwise the check would not touch the switching point.
            for (j in 1 until g.grid.n) {
                val x = g.grid.x(j)
                if (fullCellCount(g.grid, x - 0.5 * eps) != fullCellCount(g.grid, x + 2.0 * eps)) crossings++
            }
        }
        assertTrue(comparisons > 0, "Degenerate test: not a single comparison at the relative threshold")
        assertTrue(
            crossings > 0,
            "Degenerate set: on no grid does crossing the threshold change the number of full cells, "
                + "that is, the switching point is not checked",
        )
    }

    /**
     * ON INTERVALS OF SCALE <= 1 THE THRESHOLD COINCIDES WITH THE FORMER 1e-15 BITWISE.
     *
     * This is the very proof of the neutrality of the migration to a relative threshold: the characterization
     * baseline is shot on `[0,1]`, and if the threshold there is the same down to the bit, then the numbers could not have moved.
     * RAW bits are compared, not values.
     */
    @Test fun thresholdIsBitwiseUnchangedOnUnitScaleSegments() {
        val unitScale = listOf(
            "[0,1] (default, the baseline is shot on it)" to Grid.uniform(8),
            "[0,1] n=16" to Grid.uniform(16),
            "[0,0.5] (scale SMALLER than 1)" to Grid.uniform(8, 0.0, 0.5),
            "geometric [0,1]" to Grid.geometric(8, R = 2.0),
            "graded [0,1]" to Grid.graded(8, ratio = 2.0),
        )
        for ((name, grid) in unitScale) {
            val op = VolterraOperator(VolterraProblem.V2.kernel, grid, quad)
            assertBitwise(1e-15, op.breakpointInclusionEps) {
                "On an interval of scale <= 1 the threshold must coincide bitwise with the former absolute 1e-15 " +
                    "(otherwise the migration is not neutral and the baseline would have moved): grid $name, " +
                    "expected " + fmt(1e-15) + ", got " + fmt(op.breakpointInclusionEps)
            }
        }
    }

    /**
     * On an interval of LARGE scale the threshold REALLY scales and stays
     * a working tolerance — that is, the subtraction `t - eps` really changes `t`.
     *
     * It is exactly this that was broken before the fix: with an absolute 1e-15 on `[0,1000]` the expression
     * `t - 1e-15` returned EXACTLY `t` (the shift is below the ulp), and the tolerance degenerated into a strict `<`.
     */
    @Test fun thresholdActuallyScalesOnLargeSegments() {
        val grid = Grid.uniform(8, 0.0, 1000.0)
        val op = VolterraOperator(VolterraProblem.V2.kernel, grid, quad)
        val eps = op.breakpointInclusionEps
        assertTrue(eps > 1e-15, "On [0,1000] the threshold must be greater than the absolute 1e-15, got $eps")
        val x = grid.x(4)
        // The old absolute threshold is degenerate here: the subtraction does not change the number by a single bit.
        assertBitwise(x, x - 1e-15) {
            "It was expected that on [0,1000] the OLD absolute threshold is degenerate (x-1e-15 == x); " +
                "if this is not so, the motivation of the fix is wrong: x=" + fmt(x)
        }
        // And the new relative one works.
        assertTrue(
            x - eps < x,
            "The relative threshold must really shift the point: x=" + fmt(x) + ", eps=" + eps +
                ", x-eps=" + fmt(x - eps),
        )
    }

    /**
     * Interior points, including the first cell (the cache is not involved at all — the path must
     * reduce to a single truncated cell) and the last one (the cache is involved maximally).
     */
    @Test fun interiorPoints_cachedMatchesUncachedBitwise() {
        val stats = compareAll("interior points") { grid -> interiorTs(grid) }
        assertNonDegenerate(stats)
        // We require that among the comparisons there are also ones with NO full cells: otherwise the branch
        // "t inside the first cell" would stay untaken, and it is a separate one in the code.
        assertTrue(
            stats.comparisons > stats.withFullCells,
            "Degenerate set: not a single comparison without full cells is left " +
                "(${stats.comparisons} comparisons, of them with full cells ${stats.withFullCells})",
        )
    }

    /**
     * Independence of the ORDER of calls. The cache is reused by one closure for all
     * `t` (see `VolterraSecondKindSolver.applyL`), and the order of these `t` is determined by the calling
     * code: the matrix assembly, the Kulkarni iterations, the residual computation. The cell values do not
     * depend on `t` by construction, but it is exactly this that is checked: a run in the reverse and in the
     * shuffled (with a fixed seed) order must give the same bits as the
     * uncached path.
     */
    @Test fun cacheReuseIsOrderIndependent_bitwise() {
        var comparisons = 0
        for (g in gridCases()) {
            val ts = boundaryTs(g.grid) + nodeThresholdTs(g.grid) + interiorTs(g.grid)
            val reversed = ts.reversed()
            val shuffled = ts.shuffled(Random(20240513))
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid)) {
                    val expected = HashMap<String, Double>()
                    for (tc in ts) expected[tc.label] = op.apply(tc.t, integrand.u)
                    for ((orderName, order) in listOf("reverse" to reversed, "shuffled" to shuffled)) {
                        // A fresh cache for every order: what is of interest is the first filling of the cells
                        // in exactly this order of calls.
                        val cache = op.integrandCache(integrand.u)
                        for (tc in order) {
                            val actual = op.apply(tc.t, cache)
                            comparisons++
                            assertBitwise(expected.getValue(tc.label), actual) {
                                report(
                                    "order of calls: $orderName", g, k, integrand, tc,
                                    expected.getValue(tc.label), actual, op, cache,
                                )
                            }
                        }
                    }
                }
            }
        }
        assertTrue(comparisons > 0, "Degenerate test: not a single comparison was performed")
    }

    /**
     * Determinism under CONCURRENT access to one instance of the cache.
     *
     * The KDoc of [VolterraOperator.IntegrandCache] states directly: a race of two threads on one
     * cell is harmless, because `u` is pure and both compute bitwise identical numbers, while the
     * winner of `compareAndSet` determines whose array the others will see. The statement is
     * checked IN FACT: several threads start simultaneously (a barrier) and walk through
     * the same list of `t` in the same order — that is, all of them at once claim the first
     * filling of cell 0, then of cell 1 and so on. This maximizes the contention.
     *
     * The test is deterministic: a fixed number of threads, a fixed list of `t`,
     * a fixed number of repetitions; bitwise equality with the SEQUENTIAL
     * uncached baseline is checked, not "the absence of exceptions", so the outcome does not depend on
     * whether a race actually happened.
     */
    @Test fun concurrentCacheUse_isBitwiseDeterministic() {
        val grid = Grid.uniform(8)
        val op = VolterraOperator(VolterraProblem.V2exp.kernel, grid, quad)
        val basis = MinimalSplineBasis(GeneratingSystem.B, grid)
        val coeffs = DoubleArray(grid.n + 2) { i -> Math.sin(0.7 * i + 0.3) }
        // A spline, not trigonometry: exactly such functions are cached in the solver.
        val u = { s: Double -> basis.evalSpline(coeffs, s) }
        val ts = boundaryTs(grid) + nodeThresholdTs(grid) + interiorTs(grid)
        val expected = DoubleArray(ts.size) { i -> op.apply(ts[i].t, u) }

        val threads = 4
        val repeats = 3
        val pool = Executors.newFixedThreadPool(threads)
        try {
            repeat(repeats) { iteration ->
                val cache = op.integrandCache(u)
                val barrier = CyclicBarrier(threads)
                val futures = (0 until threads).map {
                    pool.submit(
                        Callable {
                            barrier.await(30, TimeUnit.SECONDS)
                            DoubleArray(ts.size) { i -> op.apply(ts[i].t, cache) }
                        },
                    )
                }
                for ((tid, future) in futures.withIndex()) {
                    val got = future.get(60, TimeUnit.SECONDS)
                    for (i in ts.indices) {
                        assertBitwise(expected[i], got[i]) {
                            "Concurrent cache: thread #$tid, repetition #$iteration, uniform n=8, " +
                                "kernel V2exp, spline evalSpline: " + tsDescription(ts[i]) + "\n" +
                                "  sequential uncached: " + fmt(expected[i]) + "\n" +
                                "  concurrent cached:   " + fmt(got[i]) + "\n" +
                                cacheContentsReport(op, grid, u, cache)
                        }
                    }
                }
                // Additionally: after the race the CONTENTS of the cache themselves must coincide with
                // the direct computation of u at the nodes — otherwise the "harmlessness" of the race is not proved,
                // and the coincidence of the integrals could turn out to be an accidental cancellation.
                val contents = cacheContentsReport(op, grid, u, cache)
                assertTrue(
                    contents.isEmpty(),
                    "After the concurrent filling the contents of the cache diverged from the direct " +
                        "computation of u (repetition #$iteration):\n$contents",
                )
            }
        } finally {
            pool.shutdownNow()
        }
    }

    /**
     * Points BEYOND the upper bound and in its neighbourhood: the uncovered branch `included == bp.size`.
     *
     * Why separately from [boundaryTs]: at `t > b` in the cached path the counter `included`
     * runs into the ARRAY BOUND (`included < bp.size`) rather than into the condition on `t`,
     * whereas in `subBreakpoints` the loop ends by the natural end of the `for`. This is
     * the only place where the two paths stop for DIFFERENT reasons, so the
     * identity of the results requires a direct check. Points `t > b` are reachable
     * in practice: the finite-difference stencil in `VolterraFirstKindSolver.deriv4` takes `t + k*h`.
     */
    private fun beyondUpperBoundTs(grid: Grid): List<TCase> {
        val res = ArrayList<TCase>()
        val span = grid.b - grid.a
        for (d in listOf(1e-16, 1e-15, 1e-14, 1e-9, 1e-3, 0.25 * span, span)) {
            res.add(TCase(grid.b + d, "t=b+$d BEYOND the upper bound (b=${grid.b})"))
        }
        // On intervals of large scale the shifts 1e-16..1e-14 lie BELOW the ulp of `b` itself
        // (ulp(1e3) ~ 2.3e-13), and `b + d` returns EXACTLY `b` — the point turns out to be not
        // beyond the bound but at it. An explicit nextUp(b) guarantees the SMALLEST possible
        // excursion beyond the interval — exactly one ulp — on ANY scale. It is it that proves
        // that the membership check is STRICT (without a tolerance), and that the cell selection of the two
        // paths coincides even at the minimal possible excess.
        res.add(TCase(Math.nextAfter(grid.b, Double.POSITIVE_INFINITY), "t=nextUp(b) (one ulp to the right of b)"))
        return res
    }

    /**
     * The neighbourhood of the bound `b` ITSELF FROM BELOW and of the adjacent node `x_n`.
     *
     * [nodeThresholdTs] walks only the INTERIOR nodes (`j in 1 until n`), so
     * the most sensitive point — `b` minus a quantity of the order of the threshold 1e-15 — was not
     * checked. It is exactly here that it is decided whether the LAST cell entered in full
     * or stayed truncated to a width of a few ulps.
     */
    private fun upperBoundNeighborhoodTs(grid: Grid): List<TCase> {
        val res = ArrayList<TCase>()
        for (d in listOf(1e-16, 1e-15, 1e-14)) {
            res.add(TCase(grid.b - d, "t=b-$d (b=${grid.b}, neighbourhood of the upper bound)"))
        }
        res.add(TCase(Math.nextAfter(grid.b, Double.NEGATIVE_INFINITY), "t=nextDown(b) (the nearest double to the left of b)"))
        // nextUp(b) MOVED to [beyondUpperBoundTs]: it is a point OUTSIDE the interval, while here
        // the neighbourhood of `b` FROM BELOW is collected. The coverage is not lost: there it is checked
        // by BOTH tests — both by the bitwise comparison and by the cross-check of the rejection.
        return res
    }

    /**
     * `t` BEYOND the upper bound: the branch of exhausting the array of nodes (`included == bp.size`).
     *
     * ON ITEM 8.3. All four functions REMAINED in the cross-check, including `evalSpline`,
     * which now throws outside the interval: [compareAll] compares the OUTCOME AS A WHOLE
     * (a number or an exception), not only the numbers. The requirement became STRICTER: the paths
     * must agree also on whether a value is computed at all.
     *
     * A FACT (measured): at a SMALL excess (`b + 1e-15` … `b + 1e-3` on `[0,1]`)
     * `evalSpline` does NOT throw, although `t > b`. The reason is that the Gauss quadrature is OPEN:
     * its nodes lie STRICTLY INSIDE the cell (the largest node of the 8-point rule is
     * 0.96029 of the half-width), and with a truncated cell `[x_{n-1}, t]` the rightmost
     * node crosses `b` only when the excess becomes comparable with the width of the
     * cell (on uniform n=4 — roughly from `d > 5.1e-3`). Therefore requiring a rejection
     * on all `t > b` would be WRONG: the check stands at the point of EVALUATION of `u`,
     * and not at the upper limit of integration. Both regimes are covered: see
     * [beyondUpperBound_bothPathsAgreeOnRejection], where BOTH outcomes are recorded.
     */
    @Test fun beyondUpperBound_cachedMatchesUncachedBitwise() {
        val stats = compareAll("points beyond the upper bound t>b") { grid -> beyondUpperBoundTs(grid) }
        assertNonDegenerate(stats)
        // All cells must be full in EVERY comparison, otherwise the set of t is chosen wrongly.
        assertTrue(
            stats.comparisons == stats.withFullCells,
            "Degenerate set: at t>b all cells must be full, but out of " +
                "${stats.comparisons} comparisons only ${stats.withFullCells} are such",
        )
    }

    /**
     * At `t > b` and with `u` NOT DEFINED outside the interval, both paths behave the SAME,
     * and at a large enough excess BOTH reject the call (item 8.3).
     *
     * It replaces the former combination "`evalSpline` × `t>b`" and CHECKS MORE than it did.
     * Previously TWO EXTRAPOLATIONS were compared — numbers that both paths obtained from
     * an undefined value. Now a coincidence of the OUTCOMES is required — including whether
     * an exception was thrown — and this is the original meaning of the test: the cache must not
     * diverge from the original on ANY input, including a bad one.
     *
     * Why this is critical exactly for the cache: it computes `u` at the nodes of the FULL cells
     * (all inside the interval), while beyond `b` go only the nodes of the TRUNCATED cell
     * `[x_{n-1}, t]`, which both paths compute identically, without the cache. A divergence of
     * the outcomes would mean that the sets of points of evaluation of `u` of the paths differ.
     *
     * NON-DEGENERACY is required EXPLICITLY in BOTH directions: among the points there must be
     * both ones where the call is REJECTED (a large excess — the quadrature nodes went beyond `b`),
     * and ones where it WENT THROUGH (a small excess — the open quadrature stayed
     * inside). Without this the test could silently degenerate into a check of one regime.
     */
    @Test fun beyondUpperBound_bothPathsAgreeOnRejection() {
        var checks = 0
        var rejectedCount = 0
        var acceptedCount = 0
        for (g in gridCases()) {
            // Only the points that ACTUALLY ended up beyond `b`: on intervals of large
            // scale `b + 1e-16` gives EXACTLY `b` (the shift is below the ulp).
            val ts = beyondUpperBoundTs(g.grid).filter { it.t > g.grid.b }
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid).filter { !it.definedOutsideSegment }) {
                    val cache = op.integrandCache(integrand.u)
                    for (tc in ts) {
                        val uncached = runCatching { op.apply(tc.t, integrand.u) }
                        val cached = runCatching { op.apply(tc.t, cache) }
                        checks++
                        if (uncached.isFailure) rejectedCount++ else acceptedCount++
                        assertSameOutcome(uncached, cached) {
                            outcomeReport("t>b with u not defined outside the interval", g, k, integrand, tc, uncached, cached)
                        }
                        if (uncached.isFailure) {
                            val e = uncached.exceptionOrNull()!!
                            assertTrue(
                                e is IllegalArgumentException,
                                "An IllegalArgumentException from the interval membership check was expected, " +
                                    "got ${e::class}: $e",
                            )
                            assertTrue(
                                (e.message ?: "").contains("MinimalSplineBasis"),
                                "The message must name the source of the rejection: \"${e.message}\"",
                            )
                        }
                    }
                }
            }
        }
        assertTrue(checks > 0, "Degenerate test: not a single comparison at t>b was performed")
        assertTrue(
            rejectedCount > 0,
            "Degenerate set: not a single call was rejected, that is, the new interval membership " +
                "check never fired (checks $checks)",
        )
        assertTrue(
            acceptedCount > 0,
            "Degenerate set: ALL calls were rejected, that is, the regime \"a small excess, " +
                "the open quadrature stayed inside the interval\" is not checked (checks $checks)",
        )
    }

    /** The neighbourhood of the upper bound `b` itself — not covered by [nodeThresholdTs]. */
    @Test fun upperBoundNeighborhood_cachedMatchesUncachedBitwise() {
        val stats = compareAll("neighbourhood of the upper bound b") { grid -> upperBoundNeighborhoodTs(grid) }
        assertNonDegenerate(stats)
    }

    /**
     * A NESTED cache: the integrand itself is computed through a cache.
     *
     * In the solver this is reached in `matrixM2`: `applyL(image)`, where `image = applyL(omega)`,
     * that is, the outer cache is filled with the VALUES OF A CACHED image. The potential
     * danger: the inner cache is computed at the nodes, and not at those `t` that the uncached
     * path would request, and an error here would double with the nesting depth.
     * The oracle is a COMPLETELY uncached double application of the operator.
     */
    @Test fun nestedCache_cachedMatchesUncachedBitwise() {
        var comparisons = 0
        var nonZero = 0
        var beyondComparisons = 0
        for (g in gridCases()) {
            val withinSegment = boundaryTs(g.grid) + interiorTs(g.grid) + upperBoundNeighborhoodTs(g.grid)
            val beyond = beyondUpperBoundTs(g.grid)
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid)) {
                    // Points t>b are added ONLY for functions defined outside the interval
                    // (item 8.3): for `evalSpline` such a call is an error, and its consistency
                    // between the paths is checked by [beyondUpperBound_bothPathsRejectUndefinedIntegrand].
                    val ts = withinSegment + beyond
                    beyondComparisons += beyond.size
                    // The oracle: both levels without a cache.
                    val innerUncached = { s: Double -> op.apply(s, integrand.u) }
                    // Under test: both levels through a cache (as in matrixM2).
                    val innerCache = op.integrandCache(integrand.u)
                    val innerCached = { s: Double -> op.apply(s, innerCache) }
                    val outerCache = op.integrandCache(innerCached)
                    for (tc in ts) {
                        // The OUTCOME AS A WHOLE is compared (item 8.3): at t>b and a spline `u`
                        // both levels may consistently reject the call — this is a coincidence too.
                        val expectedRes = runCatching { op.apply(tc.t, innerUncached) }
                        val actualRes = runCatching { op.apply(tc.t, outerCache) }
                        comparisons++
                        assertSameOutcome(expectedRes, actualRes) {
                            outcomeReport("nested cache", g, k, integrand, tc, expectedRes, actualRes)
                        }
                        if (expectedRes.isFailure) continue
                        val expected = expectedRes.getOrThrow()
                        val actual = actualRes.getOrThrow()
                        if (expected != 0.0) nonZero++
                        assertBitwise(expected, actual) {
                            "The nested cache (as in matrixM2: applyL(applyL(omega))) diverged from the completely " +
                                "uncached double application BITWISE.\n" +
                                "  grid:     " + g.name + "\n" +
                                "  kernel:   " + k.name + "\n" +
                                "  function: " + integrand.name + "\n" +
                                "  point:    " + tsDescription(tc) + "\n" +
                                "  without cache (both levels): " + fmt(expected) + "\n" +
                                "  with cache (both levels):    " + fmt(actual) + "\n" +
                                "  inner cache against direct u(node):\n" +
                                cacheContentsReport(op, g.grid, integrand.u, innerCache)
                        }
                    }
                }
            }
        }
        assertTrue(comparisons > 0, "Degenerate test: not a single comparison of the nested cache")
        assertTrue(nonZero > 0, "Degenerate test: all values of the nested cache turned out to be zero")
        // The t>b branch of the NESTED cache must stay taken: it is exactly it that
        // was the point of including [beyondUpperBoundTs] in this test. The filter above removed
        // only one function out of four, and this check does not let it silently grow
        // to a complete disappearance of the branch.
        assertTrue(
            beyondComparisons > 0,
            "Degenerate set: the nested cache was never checked at points t>b",
        )
    }

    /**
     * The cache is bound to an INSTANCE of the operator, and not only to the function.
     *
     * Why. `IntegrandCache` is an `inner class`, and in Kotlin the type of an `inner class` is NOT
     * parameterized by the outer INSTANCE, so `op2.apply(t, op1.integrandCache(u))`
     * compiles. Without a check of the owner such a call would silently give wrong
     * numbers (the values of `u` at the nodes of the grid of `op1`, the kernel at the nodes of the grid of `op2`) or
     * an `IndexOutOfBoundsException` with a coarser grid of the owner. Today such a path is not reachable in
     * the project, but moving the code into a common solver core would make it so.
     *
     * The test is not degenerate: first it is proved that the grids of the two operators are REALLY
     * different and that both operators separately work with THEIR OWN cache
     * (otherwise the exception could be thrown for any other reason).
     */
    @Test fun cacheIsBoundToOwningOperator_foreignCacheRejected() {
        val gridFine = Grid.uniform(16)
        val gridCoarse = Grid.uniform(4)
        val u = { s: Double -> Math.sin(3.0 * s) * Math.exp(-0.5 * s) }
        val opFine = VolterraOperator(VolterraProblem.V2.kernel, gridFine, quad)
        val opCoarse = VolterraOperator(VolterraProblem.V2.kernel, gridCoarse, quad)

        // The grids must be different — otherwise the defect we guard against would be imaginary.
        assertTrue(
            gridFine.breakpoints.size != gridCoarse.breakpoints.size,
            "Degenerate test: the grids of the operators coincide, substituting the cache would be harmless",
        )
        val probe = 0.5 * (gridFine.a + gridFine.b)
        // Every operator with ITS OWN cache works and gives correct numbers.
        assertBitwise(opFine.apply(probe, u), opFine.apply(probe, opFine.integrandCache(u))) {
            "An operator with ITS OWN cache must work (gridFine)"
        }
        assertBitwise(opCoarse.apply(probe, u), opCoarse.apply(probe, opCoarse.integrandCache(u))) {
            "An operator with ITS OWN cache must work (gridCoarse)"
        }

        // But a FOREIGN cache must be rejected with a clear exception — in BOTH directions.
        for ((name, pair) in listOf(
            "coarse cache into a fine operator" to (opFine to opCoarse),
            "fine cache into a coarse operator" to (opCoarse to opFine),
        )) {
            val (target, foreign) = pair
            val foreignCache = foreign.integrandCache(u)
            val error = try {
                target.apply(probe, foreignCache)
                null
            } catch (e: IllegalArgumentException) {
                e
            }
            if (error == null) {
                fail(
                    "Passing a FOREIGN cache was not rejected ($name): the call finished without " +
                        "an IllegalArgumentException. This is the very latent defect: the values of u are taken " +
                        "at the nodes of the grid of the owner of the cache, and the kernel at the nodes of the grid of the called operator, " +
                        "that is, the result is silently wrong",
                )
            }
            val message = error.message ?: ""
            assertTrue(
                message.contains("VolterraOperator") && message.contains("u(s)"),
                "The error message is unclear ($name): it must name the class of the operator " +
                    "and explain the cause (nodes of different grids). Got: \"$message\"",
            )
        }
    }

    /**
     * Consistency of the paths at `t = NaN`.
     *
     * The uncached path gives NaN: in `GaussLegendre.integrate` the condition `hi <= lo`
     * is false for NaN, so the computation continues and the NaN propagates into the sum.
     * The cached path uses THE SAME negation (`!(t <= lo)`) and not `t > lo`,
     * exactly for the branching to coincide: the variant `t > lo` would return exactly `0.0`,
     * that is, a PLAUSIBLE number instead of a signal about a bad input. What is checked
     * is exactly the consistency (both NaN), and not the bits: the payload of a NaN is not
     * specified by the arithmetic and requiring it to coincide would be excessive.
     */
    @Test fun nanArgument_bothPathsAgree() {
        var checks = 0
        for (g in gridCases()) {
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid)) {
                    val cache = op.integrandCache(integrand.u)
                    val uncached = op.apply(Double.NaN, integrand.u)
                    val cached = op.apply(Double.NaN, cache)
                    checks++
                    assertTrue(
                        uncached.isNaN(),
                        "It was expected that the uncached path at t=NaN gives NaN " +
                            "(grid ${g.name}, kernel ${k.name}, ${integrand.name}), got ${fmt(uncached)}",
                    )
                    assertTrue(
                        cached.isNaN(),
                        "The cached path diverged from the uncached one at t=NaN " +
                            "(grid ${g.name}, kernel ${k.name}, ${integrand.name}): " +
                            "without cache ${fmt(uncached)}, with cache ${fmt(cached)}. " +
                            "The likely cause: the condition of the truncated cell is written as `t > lo` " +
                            "instead of the negation `!(t <= lo)`, and at NaN the branch is silently skipped",
                    )
                }
            }
        }
        assertTrue(checks > 0, "Degenerate test: not a single NaN check was performed")
    }

    // --- The mechanics of the comparison -----------------------------------------

    private class Stats {
        var comparisons = 0
        var withFullCells = 0
        var nonZero = 0

        /** Comparisons where BOTH paths consistently rejected the call (a point outside the interval). */
        var rejected = 0
    }

    /**
     * The outcomes of the two paths coincide QUALITATIVELY: either both returned a number, or both
     * threw an exception OF ONE TYPE. The numbers themselves are compared separately, bitwise.
     *
     * A coincidence of the TYPE of the exception is mandatory: otherwise one path could fail by
     * the interval membership check and the other by running out of the array
     * of cells, and "both failed" would be a coincidence rather than an equivalence.
     */
    private fun assertSameOutcome(
        expected: Result<Double>,
        actual: Result<Double>,
        message: () -> String,
    ) {
        if (expected.isFailure != actual.isFailure) fail(message())
        if (expected.isFailure &&
            expected.exceptionOrNull()!!::class != actual.exceptionOrNull()!!::class
        ) {
            fail(message())
        }
    }

    /** Diagnostics of a divergence of the OUTCOMES (a number against an exception). */
    private fun outcomeReport(
        scenario: String,
        g: GridCase,
        k: KernelCase,
        integrand: IntegrandCase,
        tc: TCase,
        expected: Result<Double>,
        actual: Result<Double>,
    ): String = buildString {
        append("The cached and the uncached path gave outcomes DIFFERENT IN KIND.\n")
        append("  scenario: ").append(scenario).append('\n')
        append("  grid:     ").append(g.name)
            .append(" [a=").append(g.grid.a).append(", b=").append(g.grid.b).append("]\n")
        append("  kernel:   ").append(k.name).append('\n')
        append("  function: ").append(integrand.name)
            .append(if (integrand.definedOutsideSegment) " (defined outside the interval)" else " (ONLY on the interval)")
            .append('\n')
        append("  point:    ").append(tsDescription(tc)).append('\n')
        append("  without cache: ")
            .append(expected.fold({ fmt(it) }, { "exception ${it::class.simpleName}: ${it.message}" }))
            .append('\n')
        append("  with cache:    ")
            .append(actual.fold({ fmt(it) }, { "exception ${it::class.simpleName}: ${it.message}" }))
            .append('\n')
        append("  The cause matters: the cache computes u at the nodes of the FULL cells, while the uncached\n")
        append("  path does so at the nodes of the WHOLE partition. A divergence of the outcomes means that these\n")
        append("  sets of points are DIFFERENT.\n")
    }

    /**
     * Runs all the combinations (grid × kernel × integrand × t) and compares them
     * bitwise. The cache is created ONE per combination (grid, kernel, function) and serves all
     * `t` — exactly the way it lives in `VolterraSecondKindSolver.applyL`.
     */
    private fun compareAll(
        scenario: String,
        tsOf: (Grid) -> List<TCase>,
    ): Stats {
        val stats = Stats()
        for (g in gridCases()) {
            val ts = tsOf(g.grid)
            for (k in kernelCases) {
                val op = VolterraOperator(k.kernel, g.grid, quad)
                for (integrand in integrands(g.grid)) {
                    val cache = op.integrandCache(integrand.u)
                    for (tc in ts) {
                        // BOTH paths are called through runCatching, and the OUTCOME AS A WHOLE is compared.
                        // Since item 8.3 there are two outcomes: a number or an exception (if a quadrature node
                        // went beyond the interval). The requirement is NOT WEAKENED but EXTENDED: previously
                        // only a coincidence of the numbers was required, now also a coincidence of the very
                        // fact of a rejection. It is exactly here that the main risk of the cache is caught: it computes `u`
                        // at the nodes of the FULL cells, while the uncached path does so at the nodes of the WHOLE partition;
                        // if the sets of points diverged, one path would throw and the other would not.
                        val expectedRes = runCatching { op.apply(tc.t, integrand.u) }
                        val actualRes = runCatching { op.apply(tc.t, cache) }
                        stats.comparisons++
                        if (fullCellCount(g.grid, tc.t) > 0) stats.withFullCells++
                        assertSameOutcome(expectedRes, actualRes) {
                            outcomeReport(scenario, g, k, integrand, tc, expectedRes, actualRes)
                        }
                        if (expectedRes.isFailure) {
                            stats.rejected++
                            continue
                        }
                        val expected = expectedRes.getOrThrow()
                        val actual = actualRes.getOrThrow()
                        if (expected != 0.0) stats.nonZero++
                        assertBitwise(expected, actual) {
                            report(scenario, g, k, integrand, tc, expected, actual, op, cache)
                        }
                    }
                }
            }
        }
        return stats
    }

    /**
     * Protection against a degeneration of the check itself: if all compared values turned out to be zeros
     * or no configuration involved the cache, the test would be green about nothing.
     */
    private fun assertNonDegenerate(stats: Stats) {
        assertTrue(stats.comparisons > 0, "Degenerate test: not a single comparison was performed")
        assertTrue(
            stats.withFullCells > 0,
            "Degenerate test: no comparison had full cells, that is, the cache is not involved",
        )
        assertTrue(
            stats.nonZero > 0,
            "Degenerate test: all compared values turned out to be zero (${stats.comparisons} comparisons)",
        )
    }

    /**
     * Bitwise comparison.
     *
     * RAW bits are compared, not values through `==`. The reason for the choice: `==` for doubles
     * also distinguishes numbers bitwise, BUT declares `0.0 == -0.0` (different signs of zero —
     * this is already a different result of the accumulation, it must not be let through) and `NaN != NaN`
     * (a coinciding "bad" result of both paths is not a divergence of the paths). The comparison
     * `doubleToRawLongBits` is free of both caveats. A tolerance is not used
     * on principle: the meaning of the check is the absence of ANY divergence, even of one bit.
     */
    private fun assertBitwise(expected: Double, actual: Double, message: () -> String) {
        if (!sameBits(expected, actual)) fail(message())
    }

    private fun sameBits(x: Double, y: Double): Boolean =
        java.lang.Double.doubleToRawLongBits(x) == java.lang.Double.doubleToRawLongBits(y)

    private fun bits(x: Double): String =
        "0x" + java.lang.Long.toHexString(java.lang.Double.doubleToRawLongBits(x))

    private fun fmt(x: Double): String = "$x [${bits(x)}]"

    /**
     * The number of FULL cells of the grid in the partition [a,t] (repeats the selection of both paths).
     *
     * The threshold is taken from the OPERATOR ITSELF (it is relative and depends on the scale of the
     * interval) and is not hard-wired as a constant: otherwise the diagnostics and the non-degeneracy
     * checks would lie on grids of large scale.
     */
    private fun fullCellCount(grid: Grid, t: Double): Int {
        if (t <= grid.a) return 0
        val bp = grid.breakpoints
        val eps = VolterraOperator(kernelCases[0].kernel, grid, quad).breakpointInclusionEps
        var included = 0
        while (included < bp.size && bp[included] < t - eps) included++
        return maxOf(0, included - 1)
    }

    private fun tsDescription(tc: TCase): String = "${tc.label}, t=${fmt(tc.t)}"

    // --- Diagnostics --------------------------------------------------------------

    /**
     * A diagnostic message about a divergence. It must answer the questions: at which `t`,
     * on which grid, with which kernel and which function, in which cell and which node, and
     * what BOTH values are. It is built only on a failure, so it may be detailed.
     */
    private fun report(
        scenario: String,
        g: GridCase,
        k: KernelCase,
        integrand: IntegrandCase,
        tc: TCase,
        expected: Double,
        actual: Double,
        op: VolterraOperator,
        cache: VolterraOperator.IntegrandCache,
    ): String {
        val ulp = Math.ulp(expected)
        val deltaUlps = if (ulp > 0.0) (actual - expected) / ulp else Double.NaN
        val sb = StringBuilder()
        sb.append("The cached path VolterraOperator.apply(t, cache) diverged from the uncached ")
            .append("apply(t, u) BITWISE.\n")
        sb.append("  scenario:       ").append(scenario).append('\n')
        sb.append("  grid:           ").append(g.name)
            .append(" [a=").append(g.grid.a).append(", b=").append(g.grid.b).append("]\n")
        sb.append("  kernel:         ").append(k.name).append('\n')
        sb.append("  function u:     ").append(integrand.name).append('\n')
        sb.append("  point:          ").append(tsDescription(tc)).append('\n')
        sb.append("  full cells:     ").append(fullCellCount(g.grid, tc.t)).append('\n')
        sb.append("  expected (without cache): ").append(fmt(expected)).append('\n')
        sb.append("  got (with cache):         ").append(fmt(actual)).append('\n')
        sb.append("  difference:     ").append(actual - expected)
            .append(" = ").append(deltaUlps).append(" ulp\n")
        val contents = cacheContentsReport(op, g.grid, integrand.u, cache)
        if (contents.isNotEmpty()) {
            sb.append("  cache contents:\n").append(contents)
        } else {
            sb.append("  the cache contents coincide with the direct u(node) in all cells and nodes,\n")
            sb.append("  hence the divergence arose in the ARITHMETIC of the accumulation of the sum ")
                .append("(the order of factors/summands).\n")
            sb.append(cellLocalization(op, g.grid, integrand.u, cache))
        }
        return sb.toString()
    }

    /**
     * Compares the CONTENTS of the cache with a direct computation of `u` at the nodes of the full cells. The nodes
     * are reproduced by the same formula as in the quadrature (`mid + half * refNodes[q]`),
     * so a divergence here means either different nodes or different values.
     *
     * @return an empty string if everything coincides; otherwise a description of the first divergences.
     */
    private fun cacheContentsReport(
        op: VolterraOperator,
        grid: Grid,
        u: (Double) -> Double,
        cache: VolterraOperator.IntegrandCache,
    ): String {
        val bp = grid.breakpoints
        val sb = StringBuilder()
        var reported = 0
        for (c in 0 until bp.size - 1) {
            val lo = bp[c]
            val hi = bp[c + 1]
            if (hi <= lo) continue
            val half = 0.5 * (hi - lo)
            val mid = 0.5 * (hi + lo)
            val cached = cache.values(c)
            for (q in refNodes.indices) {
                val s = mid + half * refNodes[q]
                val direct = u(s)
                if (!sameBits(direct, cached[q])) {
                    if (reported < 5) {
                        sb.append("    cell c=").append(c)
                            .append(" [").append(lo).append(", ").append(hi).append("], node q=").append(q)
                            .append(", s=").append(fmt(s)).append('\n')
                            .append("      direct u(s) = ").append(fmt(direct)).append('\n')
                            .append("      from cache  = ").append(fmt(cached[q])).append('\n')
                    }
                    reported++
                }
            }
        }
        if (reported > 5) sb.append("    ... and ").append(reported - 5).append(" more divergences\n")
        return sb.toString()
    }

    /**
     * Localization of the cell starting from which the paths diverge, when the cache contents are correct
     * (the case of a permutation of factors/summands). The trick: we take `t` in the middle of the cell `m`,
     * then exactly the cells `0..m-1` turn out to be full. The smallest `m` at which the paths
     * diverged points to the cell `m-1` as the first corrupted one.
     */
    private fun cellLocalization(
        op: VolterraOperator,
        grid: Grid,
        u: (Double) -> Double,
        cache: VolterraOperator.IntegrandCache,
    ): String {
        val bp = grid.breakpoints
        for (m in 1 until bp.size - 1) {
            val probe = 0.5 * (bp[m] + bp[m + 1])
            val expected = op.apply(probe, u)
            val actual = op.apply(probe, cache)
            if (!sameBits(expected, actual)) {
                return "  the first corrupted FULL cell: c=" + (m - 1) +
                    " [" + bp[m - 1] + ", " + bp[m] + "]\n" +
                    "  (probe t=" + fmt(probe) + " with exactly " + m + " full cells: " +
                    "without cache " + fmt(expected) + ", with cache " + fmt(actual) + ")\n"
            }
        }
        return "  localizing the cell by probes failed: at the probe t (the midpoints of the cells) both paths\n" +
            "  gave the same bits — the divergence either falls on the truncated cell [x_last, t],\n" +
            "  or cancelled accidentally at the probes due to rounding\n"
    }
}
